// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.diguage.truman.netty.protobuf2;

public final class MyDataInfo {
  private MyDataInfo() {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
      (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface MyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyMessage)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用 data_type 来标识传的是哪一个枚举类型？
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     *
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();

    /**
     * <pre>
     * 用 data_type 来标识传的是哪一个枚举类型？
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     *
     * @return The dataType.
     */
    com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType getDataType();

    /**
     * <code>.Student student = 2;</code>
     *
     * @return Whether the student field is set.
     */
    boolean hasStudent();

    /**
     * <code>.Student student = 2;</code>
     *
     * @return The student.
     */
    com.diguage.truman.netty.protobuf2.MyDataInfo.Student getStudent();

    /**
     * <code>.Student student = 2;</code>
     */
    com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder();

    /**
     * <code>.Worker worker = 3;</code>
     *
     * @return Whether the worker field is set.
     */
    boolean hasWorker();

    /**
     * <code>.Worker worker = 3;</code>
     *
     * @return The worker.
     */
    com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getWorker();

    /**
     * <code>.Worker worker = 3;</code>
     */
    com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder();

    public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataBodyCase getDataBodyCase();
  }

  /**
   * Protobuf type {@code MyMessage}
   */
  public static final class MyMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MyMessage)
    MyMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private MyMessage() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private MyMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                input.readMessage(com.diguage.truman.netty.protobuf2.MyDataInfo.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_).toBuilder();
              }
              dataBody_ =
                input.readMessage(com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable(); TODO
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_MyMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.class, com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.Builder.class);
    }

    /**
     * <pre>
     * 定义一个枚举
     * </pre>
     * <p>
     * Protobuf enum {@code MyMessage.DataType}
     */
    public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 在 proto3 中，要求 enum 的编号从 0 开始
       * </pre>
       *
       * <code>StudentType = 0;</code>
       */
      StudentType(0),
      /**
       * <code>WorkerType = 1;</code>
       */
      WorkerType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 在 proto3 中，要求 enum 的编号从 0 开始
       * </pre>
       *
       * <code>StudentType = 0;</code>
       */
      public static final int StudentType_VALUE = 0;
      /**
       * <code>WorkerType = 1;</code>
       */
      public static final int WorkerType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0:
            return StudentType;
          case 1:
            return WorkerType;
          default:
            return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
      internalGetValueMap() {
        return internalValueMap;
      }

      private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.forNumber(number);
          }
        };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }

      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyMessage.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;

    public enum DataBodyCase
      implements com.google.protobuf.Internal.EnumLite,
      com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STUDENT(2),
      WORKER(3),
      DATABODY_NOT_SET(0);
      private final int value;

      private DataBodyCase(int value) {
        this.value = value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2:
            return STUDENT;
          case 3:
            return WORKER;
          case 0:
            return DATABODY_NOT_SET;
          default:
            return null;
        }
      }

      public int getNumber() {
        return this.value;
      }
    }

    ;

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
        dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;

    /**
     * <pre>
     * 用 data_type 来标识传的是哪一个枚举类型？
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     *
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override
    public int getDataTypeValue() {
      return dataType_;
    }

    /**
     * <pre>
     * 用 data_type 来标识传的是哪一个枚举类型？
     * </pre>
     *
     * <code>.MyMessage.DataType data_type = 1;</code>
     *
     * @return The dataType.
     */
    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType result = com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.valueOf(dataType_);
      return result == null ? com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.UNRECOGNIZED : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;

    /**
     * <code>.Student student = 2;</code>
     *
     * @return Whether the student field is set.
     */
    @java.lang.Override
    public boolean hasStudent() {
      return dataBodyCase_ == 2;
    }

    /**
     * <code>.Student student = 2;</code>
     *
     * @return The student.
     */
    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.Student getStudent() {
      if (dataBodyCase_ == 2) {
        return (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_;
      }
      return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
    }

    /**
     * <code>.Student student = 2;</code>
     */
    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 2) {
        return (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_;
      }
      return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
    }

    public static final int WORKER_FIELD_NUMBER = 3;

    /**
     * <code>.Worker worker = 3;</code>
     *
     * @return Whether the worker field is set.
     */
    @java.lang.Override
    public boolean hasWorker() {
      return dataBodyCase_ == 3;
    }

    /**
     * <code>.Worker worker = 3;</code>
     *
     * @return The worker.
     */
    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getWorker() {
      if (dataBodyCase_ == 3) {
        return (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_;
      }
      return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
    }

    /**
     * <code>.Worker worker = 3;</code>
     */
    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder() {
      if (dataBodyCase_ == 3) {
        return (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_;
      }
      return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (dataType_ != com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.StudentType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.StudentType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage)) {
        return super.equals(obj);
      }
      com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage other = (com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getStudent()
            .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getWorker()
            .equals(other.getWorker())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + WORKER_FIELD_NUMBER;
          hash = (53 * hash) + getWorker().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MyMessage)
      com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.class, com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.Builder.class);
      }

      // Construct using com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstanceForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage build() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage buildPartial() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage result = new com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (workerBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = workerBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage) {
          return mergeFrom((com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage other) {
        if (other == com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case WORKER: {
            mergeWorker(other.getWorker());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;

      public DataBodyCase
      getDataBodyCase() {
        return DataBodyCase.forNumber(
          dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;

      /**
       * <pre>
       * 用 data_type 来标识传的是哪一个枚举类型？
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       *
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override
      public int getDataTypeValue() {
        return dataType_;
      }

      /**
       * <pre>
       * 用 data_type 来标识传的是哪一个枚举类型？
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       *
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {

        dataType_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 用 data_type 来标识传的是哪一个枚举类型？
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       *
       * @return The dataType.
       */
      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType result = com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.valueOf(dataType_);
        return result == null ? com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType.UNRECOGNIZED : result;
      }

      /**
       * <pre>
       * 用 data_type 来标识传的是哪一个枚举类型？
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       *
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        dataType_ = value.getNumber();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 用 data_type 来标识传的是哪一个枚举类型？
       * </pre>
       *
       * <code>.MyMessage.DataType data_type = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDataType() {

        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student, com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder> studentBuilder_;

      /**
       * <code>.Student student = 2;</code>
       *
       * @return Whether the student field is set.
       */
      @java.lang.Override
      public boolean hasStudent() {
        return dataBodyCase_ == 2;
      }

      /**
       * <code>.Student student = 2;</code>
       *
       * @return The student.
       */
      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_;
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
        }
      }

      /**
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(com.diguage.truman.netty.protobuf2.MyDataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }

      /**
       * <code>.Student student = 2;</code>
       */
      public Builder setStudent(
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }

      /**
       * <code>.Student student = 2;</code>
       */
      public Builder mergeStudent(com.diguage.truman.netty.protobuf2.MyDataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
            dataBody_ != com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance()) {
            dataBody_ = com.diguage.truman.netty.protobuf2.MyDataInfo.Student.newBuilder((com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_)
              .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }

      /**
       * <code>.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>.Student student = 2;</code>
       */
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }

      /**
       * <code>.Student student = 2;</code>
       */
      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_;
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
        }
      }

      /**
       * <code>.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student, com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder>
      getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.diguage.truman.netty.protobuf2.MyDataInfo.Student, com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder>(
            (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) dataBody_,
            getParentForChildren(),
            isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();
        ;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker, com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder> workerBuilder_;

      /**
       * <code>.Worker worker = 3;</code>
       *
       * @return Whether the worker field is set.
       */
      @java.lang.Override
      public boolean hasWorker() {
        return dataBodyCase_ == 3;
      }

      /**
       * <code>.Worker worker = 3;</code>
       *
       * @return The worker.
       */
      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getWorker() {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_;
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return workerBuilder_.getMessage();
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
        }
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(com.diguage.truman.netty.protobuf2.MyDataInfo.Worker value) {
        if (workerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          workerBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder setWorker(
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder builderForValue) {
        if (workerBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          workerBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder mergeWorker(com.diguage.truman.netty.protobuf2.MyDataInfo.Worker value) {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
            dataBody_ != com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance()) {
            dataBody_ = com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.newBuilder((com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_)
              .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            workerBuilder_.mergeFrom(value);
          }
          workerBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      public Builder clearWorker() {
        if (workerBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          workerBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder getWorkerBuilder() {
        return getWorkerFieldBuilder().getBuilder();
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder getWorkerOrBuilder() {
        if ((dataBodyCase_ == 3) && (workerBuilder_ != null)) {
          return workerBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_;
          }
          return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
        }
      }

      /**
       * <code>.Worker worker = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker, com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder>
      getWorkerFieldBuilder() {
        if (workerBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
          }
          workerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.diguage.truman.netty.protobuf2.MyDataInfo.Worker, com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder, com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder>(
            (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) dataBody_,
            getParentForChildren(),
            isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();
        ;
        return workerBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage();
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
      PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Student)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 在 Student 类中有一个属性名称为 id 类型为 int32，1表示属性序号，不是值
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();
  }

  /**
   * <pre>
   * 会在 StudentPOJO 外部类生成一个内部类 Student，
   * </pre>
   * <p>
   * Protobuf type {@code Student}
   */
  public static final class Student extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Student)
    StudentOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Student() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Student(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Student_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          com.diguage.truman.netty.protobuf2.MyDataInfo.Student.class, com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;

    /**
     * <pre>
     * 在 Student 类中有一个属性名称为 id 类型为 int32，1表示属性序号，不是值
     * </pre>
     *
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.Student)) {
        return super.equals(obj);
      }
      com.diguage.truman.netty.protobuf2.MyDataInfo.Student other = (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) obj;

      if (getId()
        != other.getId()) return false;
      if (!getName()
        .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.diguage.truman.netty.protobuf2.MyDataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * 会在 StudentPOJO 外部类生成一个内部类 Student，
     * </pre>
     * <p>
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Student)
      com.diguage.truman.netty.protobuf2.MyDataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.diguage.truman.netty.protobuf2.MyDataInfo.Student.class, com.diguage.truman.netty.protobuf2.MyDataInfo.Student.Builder.class);
      }

      // Construct using com.diguage.truman.netty.protobuf2.MyDataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Student getDefaultInstanceForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Student build() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Student buildPartial() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student result = new com.diguage.truman.netty.protobuf2.MyDataInfo.Student(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.Student) {
          return mergeFrom((com.diguage.truman.netty.protobuf2.MyDataInfo.Student) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.diguage.truman.netty.protobuf2.MyDataInfo.Student other) {
        if (other == com.diguage.truman.netty.protobuf2.MyDataInfo.Student.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.diguage.truman.netty.protobuf2.MyDataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_;

      /**
       * <pre>
       * 在 Student 类中有一个属性名称为 id 类型为 int32，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 id = 1;</code>
       *
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      /**
       * <pre>
       * 在 Student 类中有一个属性名称为 id 类型为 int32，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 id = 1;</code>
       *
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 在 Student 类中有一个属性名称为 id 类型为 int32，1表示属性序号，不是值
       * </pre>
       *
       * <code>int32 id = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";

      /**
       * <code>string name = 2;</code>
       *
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string name = 2;</code>
       *
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string name = 2;</code>
       *
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       *
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.diguage.truman.netty.protobuf2.MyDataInfo.Student DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.diguage.truman.netty.protobuf2.MyDataInfo.Student();
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
      PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WorkerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Worker)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     *
     * @return The age.
     */
    int getAge();
  }

  /**
   * Protobuf type {@code Worker}
   */
  public static final class Worker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Worker)
    WorkerOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Worker.newBuilder() to construct.
    private Worker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Worker() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
      return new Worker();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Worker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Worker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.class, com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;

    /**
     * <code>int32 age = 2;</code>
     *
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.Worker)) {
        return super.equals(obj);
      }
      com.diguage.truman.netty.protobuf2.MyDataInfo.Worker other = (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) obj;

      if (!getName()
        .equals(other.getName())) return false;
      if (getAge()
        != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.diguage.truman.netty.protobuf2.MyDataInfo.Worker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code Worker}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Worker)
      com.diguage.truman.netty.protobuf2.MyDataInfo.WorkerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Worker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.class, com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.Builder.class);
      }

      // Construct using com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.internal_static_Worker_descriptor;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getDefaultInstanceForType() {
        return com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance();
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker build() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker buildPartial() {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker result = new com.diguage.truman.netty.protobuf2.MyDataInfo.Worker(this);
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) {
          return mergeFrom((com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.diguage.truman.netty.protobuf2.MyDataInfo.Worker other) {
        if (other == com.diguage.truman.netty.protobuf2.MyDataInfo.Worker.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        com.diguage.truman.netty.protobuf2.MyDataInfo.Worker parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.diguage.truman.netty.protobuf2.MyDataInfo.Worker) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";

      /**
       * <code>string name = 1;</code>
       *
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       *
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       *
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       *
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int age_;

      /**
       * <code>int32 age = 2;</code>
       *
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }

      /**
       * <code>int32 age = 2;</code>
       *
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 age = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearAge() {

        age_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Worker)
    }

    // @@protoc_insertion_point(class_scope:Worker)
    private static final com.diguage.truman.netty.protobuf2.MyDataInfo.Worker DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.diguage.truman.netty.protobuf2.MyDataInfo.Worker();
    }

    public static com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Worker>
      PARSER = new com.google.protobuf.AbstractParser<Worker>() {
      @java.lang.Override
      public Worker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Worker(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Worker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Worker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.diguage.truman.netty.protobuf2.MyDataInfo.Worker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMessage_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Worker_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_Worker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\"\244\001\n\tMyMessage\022&\n\tdata_ty" +
        "pe\030\001 \001(\0162\023.MyMessage.DataType\022\033\n\007student" +
        "\030\002 \001(\0132\010.StudentH\000\022\031\n\006worker\030\003 \001(\0132\007.Wor" +
        "kerH\000\"+\n\010DataType\022\017\n\013StudentType\020\000\022\016\n\nWo" +
        "rkerType\020\001B\n\n\010dataBody\"#\n\007Student\022\n\n\002id\030" +
        "\001 \001(\005\022\014\n\004name\030\002 \001(\t\"#\n\006Worker\022\014\n\004name\030\001 " +
        "\001(\t\022\013\n\003age\030\002 \001(\005B2\n\"com.diguage.truman.n" +
        "etty.protobuf2B\nMyDataInfoH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
        });
    internal_static_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_MyMessage_descriptor,
      new java.lang.String[]{"DataType", "Student", "Worker", "DataBody",});
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_Student_descriptor,
      new java.lang.String[]{"Id", "Name",});
    internal_static_Worker_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_Worker_descriptor,
      new java.lang.String[]{"Name", "Age",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
