== Field

属性操作方法 `Field#set(Object obj, Object value)` 和 `Field#get(Object obj)` 底层都是委托到 `jdk.internal.reflect.FieldAccessor` 实现。

`FieldAccessor` 接口有很多的实现，`FieldAccessor` 接口实例是通过 `jdk.internal.reflect.ReflectionFactory` 这个工厂构造的：

.jdk.internal.reflect.ReflectionFactory
[source,java,{source_attr}]
----
    public FieldAccessor newFieldAccessor(Field field, boolean override) {
        checkInitted();

        Field root = langReflectAccess.getRoot(field);
        if (root != null) {
            // FieldAccessor will use the root unless the modifiers have
            // been overrridden
            if (root.getModifiers() == field.getModifiers() || !override) {
                field = root;
            }
        }
        return UnsafeFieldAccessorFactory.newFieldAccessor(field, override);
    }
----

最终委托到 `UnsafeFieldAccessorFactory#newFieldAccessor()`。

`UnsafeObjectFieldAccessorImpl` 中除了 `get(Object obj)` 和 `set(Object obj, Object value)` 方法，其他方法都是直接抛出 `IllegalArgumentException`。而 `get(Object obj)` 和 `set(Object obj, Object value)` 底层分别依赖于 `jdk.internal.misc.Unsafe` 的 `putObject(obj, fieldOffset, value)` 和 `getObject(obj, fieldOffset)` 方法。而属性的内存偏移地址是在 `UnsafeObjectFieldAccessorImpl` 的父类 `UnsafeFieldAccessorImpl` 的构造函数中计算出来的。

属性反射操作 `Field` 的 `setXX` 和 `getXX` 方法最终委托到 `jdk.internal.misc.Unsafe` 的 `putXX` 和 `getXX` 方法，而属性的内存偏移地址是通过 `jdk.internal.misc.Unsafe` 的 `staticFieldBase()`、`staticFieldOffset` 和 `objectFieldOffset` 几个方法计算的。

=== 参考资料

. http://www.throwable.club/2018/12/16/java-reflection-implementance/[深入分析Java反射(七)-简述反射调用的底层实现 - Throwable's Blog]